export default {
    email           : '',
    password        : '',
    confirm_password: '',
    title           : '',
    first_name      : '',
    last_name       : '',
    phone1          : '',
    age             : false,
    errors          : {
        title           : '',
        email           : '',
        password        : '',
        confirm_password: '',
        first_name      : '',
        last_name       : '',
        phone1          : '',
        age             : '',
    },
    validation      : {
        title           : false,
        email           : false,
        password        : false,
        confirm_password: false,
        first_name      : false,
        last_name       : false,
        phone1          : false,
        age             : false,
    },
    isFormValid     : false,
    isSubmitting    : false,
    showModal       : false,
    clientTitles    : {},
};
